spring.application.name=order-service
server.port=8081
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.initial-instance-info-replication-interval-seconds=10
eureka.instance.lease-renewal-interval-in-seconds=10

# Circuit Breaker Configuration - case-sensitive name matching annotation
resilience4j.circuitbreaker.instances.paymentServiceCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentServiceCB.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.paymentServiceCB.sliding-window-size=2
resilience4j.circuitbreaker.instances.paymentServiceCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentServiceCB.automatic-transition-from-open-to-half-open-enabled=true

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
